apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.argocd.destination.server }}
    namespace: {{ .Values.istio.namespace }}
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    path: istio
    chart: istiod
    targetRevision: {{ .Values.istio.version }}
